server:
  port: 8080

spring:
  application:
    name: Effective
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver               # mysql驱动包
    url: jdbc:mysql://121.37.186.99:3306/nbcb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: public
    password: test

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example    # 所有Entity别名类所在包
#
#eureka:
#  client:
#    # 表示是否将自己注册进Eurekaserver默认为true。
#    register-with-eureka: true
#    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka

